### ISSUE TITLE
Bars and Tones

### ISSUE THREAD

**Issue by marcverhagen** [clamsproject/clams-apps#4]
Status:
- Mostly done
- No major problems
- Evaluation done based on images in an informal way
- Tool needs to be updated to deal with SDK changes
	- now creates a MMIF from 6 months ago
	- do this when new SDK is stable enough

WGBH provided feedback which may need to be dealt with and WGBH is expecting an updated version.

Needs more formal evaluation.

**Comment by keighrim** [comment]
The app is implemented at https://github.com/clamsproject/app-barsdetection, and further evaluation is planned at https://github.com/clamsproject/app-barsdetection/blob/a06390a97cf40477de67cc8e2ed18b9d80fc0126/evaluation.md. Closing this issue as updates are being and will be logged into the `README.md`.
