### ISSUE TITLE
Slate Recognition

### ISSUE THREAD

**Issue by marcverhagen** [clamsproject/clams-apps#5]
Status on recognizing the extends
- Mostly done
- No major problems
- Evaluation done based on images in an informal way
- Tool needs to be updated to deal with SDK changes
  - Now creates a MMIF from 6 months ago
- Is WGBH expecting a new version? Do we have feedback from them?
- Need to have more formal evaluation.

On recognizing Slate content
- VIA tool for annotation almost set up
  - Annotating boxes, type in the text and type boxes as key, value or other
  - Need to decide on initial set of keys
- Existing software for parsing tables may be useful.

**Comment by keighrim** [comment]
The app is implemented at https://github.com/clamsproject/app-slate-textdetection, and further evaluation is planned at https://github.com/clamsproject/app-slatedetection/blob/83319e6b411a54b8da63fc82c10ea626f657dfc5/evaluation.md. Closing this issue as updates are being and will be logged into the `README.md`.
