### ISSUE TITLE
Audio Segmenter

### ISSUE THREAD

**Issue by marcverhagen** [clamsproject/clams-apps#6]
Status
- not wrapped in MMIF
- first round of feedback, not dealt with yet
  - should be week of work
- needs evaluation
  - initial evaluations gave error rates from 1-5-%, not clear what that means
  - Vicky to get some precision/recall numbers for speech
  - also adding a confusion matrix
- making it a CLAMS tool
  - less than a week

We need to improve the performance, but this is not highest priority for September 2020. Focus on producing MMIF and running this as an application.

**Comment by keighrim** [comment]
A prototype version is available at https://github.com/clamsproject/app-audio-segmenter with all evaluation mentioned above. Closing this issue.
