### ISSUE TITLE
Kaldi

### ISSUE THREAD

**Issue by marcverhagen** [clamsproject/clams-apps#8]
Vicky poking at PyTorch and read some papers.
(PyTorch was used for Slate classifier)

Need to figure out how to use the Segmenter output.

**Comment by keighrim** [comment]
PUA Kaldi is wrapped at https://github.com/clamsproject/app-puakaldi-wrapper by @angus-lherrou . Segmented version is also available at https://github.com/clamsproject/app-puakaldi-segmented-wrapper . I hope we can merge those into a single repository once we figure out https://github.com/clamsproject/clams-python/issues/29. Closing this issue.
